name: inspection
description: 巡检--设备使用过程中相关巡检员进行安全隐患排查

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  fish_redux: ^0.1.5
  path_provider: ^0.5.0+1
  shared_preferences: ^0.5.1+1
  fluttertoast: ^3.0.1
  dio: 2.1.2
  barcode_scan: ^0.0.4

dev_dependencies:

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - images/ic_home_normal.png
   - images/ic_home_press.png
   - images/ic_avatar.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

